urdf_file_name: "hubo_description.urdf"
fixed_frame: "base_footprint"
joint_names: [ [ "WAIST", "RIGHT_SHOULDER_PITCH", "RIGHT_SHOULDER_ROLL", "RIGHT_SHOULDER_YAW", "RIGHT_ELBOW", "RIGHT_WRIST_YAW", "RIGHT_WRIST_PITCH", "RIGHT_WRIST_YAW_2" ] ]
joint_ordering: [ "WAIST", "RIGHT_SHOULDER_PITCH", "RIGHT_SHOULDER_ROLL", "RIGHT_SHOULDER_YAW", "RIGHT_ELBOW", "RIGHT_WRIST_YAW", "RIGHT_WRIST_PITCH", "RIGHT_WRIST_YAW_2" ]
ee_fixed_joints: [ "RIGHT_HAND" ]
starting_config: [ 0.0, 0.78852112, -0.14649155, -0.17695991, -1.86374666, -0.09144152, -0.46006443, -0.1494651 ]
collision_file_name: "collision_hubo8.yaml"
collision_nn_file: "hubo8_nn"
path_to_src: "/home/rakita/catkin_ws/src/relaxed_ik/src"
axis_types: [ [ "z", "y", "x", "z", "y", "z", "y", "z" ] ]
velocity_limits: [ 2.0, 4.25424005174, 4.25424005174, 7.64454212374, 7.64454212374, 8.90117918517, 14.6607657168, 14.6607657168 ]
joint_limits: [ [-1.0,1.0], [-4.53785605519,1.3962634016], [-3.66519142919,0.52], [-2.2,2.2], [-2.96705972839,-0.5], [-2.96705972839,2.96705972839], [-1.57079632679,1.57079632679], [-5.0,5.0] ]
displacements: [ [ [0.0,-0.242,0.456], [0.0,0.0,0.0], [0.0,0.0,0.0], [0.035,0.0,-0.35], [-0.035,0.0,-0.34], [0.0,0.0,0.0], [0.0,0.0,0.0326], [0.0,0.0,-0.2] ] ]
disp_offsets: [ [0.0,0.0,0.0] ]
rot_offsets: [ [ [0.0,0.0,0.0], [0.0,0.0,0.0], [0.0,0.0,0.0], [0.0,0.0,0.0], [0.0,0.0,0.0], [0.0,0.0,0.0], [0.0,0.0,0.0], [0.0,0.0,0.0] ] ]
joint_types: [ [ "revolute", "revolute", "revolute", "revolute", "revolute", "revolute", "revolute", "revolute" ] ]
joint_state_define_func_file: "hubo8_joint_state_define"
