urdf_file_name: "jaco7.urdf"
fixed_frame: "root"
joint_names: [ [ "j2s7s300_joint_1", "j2s7s300_joint_2", "j2s7s300_joint_3", "j2s7s300_joint_4", "j2s7s300_joint_5", "j2s7s300_joint_6", "j2s7s300_joint_7" ] ]
joint_ordering: [ "j2s7s300_joint_1", "j2s7s300_joint_2", "j2s7s300_joint_3", "j2s7s300_joint_4", "j2s7s300_joint_5", "j2s7s300_joint_6", "j2s7s300_joint_7" ]
ee_fixed_joints: [ "j2s7s300_joint_end_effector" ]
starting_config: [ 0.0, 3.596565083, 0.0, 5.19409985393, 0.0, 3.14159265359, 0.0 ]
collision_file_name: "collision_jaco7.yaml"
collision_nn_file: "jaco7_nn"
path_to_src: "/home/rakita/catkin_ws/src/relaxed_ik/src"
thread_dofs: [  ] 
axis_types: [ [ "z", "z", "z", "z", "z", "z", "z" ] ]
velocity_limits: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]
joint_limits: [ [-6.28318530718,6.28318530718], [0.820304748437,5.46288055874], [-6.28318530718,6.28318530718], [0.523598775598,5.75958653158], [-6.28318530718,6.28318530718], [1.1344640138,5.14872129338], [-6.28318530718,6.28318530718] ]
displacements: [ [ [0.0,0.0016,-0.11875], [0.0,-0.205,0.0], [0.0,0.0,-0.205], [0.0,0.2073,-0.0114], [0.0,0.0,-0.10375], [0.0,0.10375,0.0], [0.0,0.0,-0.16] ] ]
disp_offsets: [ [0.0,0.0,0.15675] ]
rot_offsets: [ [ [0.0,3.14159265359,0.0], [-1.57079632679,0.0,3.14159265359], [-1.57079632679,0.0,0.0], [1.57079632679,0.0,3.14159265359], [-1.57079632679,0.0,3.14159265359], [1.57079632679,0.0,3.14159265359], [-1.57079632679,0.0,3.14159265359] ] ]
joint_types: [ [ "continuous", "revolute", "continuous", "revolute", "continuous", "revolute", "continuous" ] ]
joint_state_define_func_file: "jaco7_joint_state_define"
