urdf_file_name: "panda_arm_hand.urdf"
fixed_frame: "panda_link0"
joint_names: [ [ "panda_joint1", "panda_joint2", "panda_joint3", "panda_joint4", "panda_joint5", "panda_joint6", "panda_joint7", "panda_joint8"  ] ]
joint_ordering: [ "panda_joint1", "panda_joint2", "panda_joint3", "panda_joint4", "panda_joint5", "panda_joint6", "panda_joint7" ]
ee_fixed_joints: [ "panda_hand_joint" ]
starting_config: [ 0.0, 0.0, 0.0, -1.57, 0.0, 3.14, 0.0 ]
collision_file_name: "collision_panda.yaml"
collision_nn_file: "panda_arm_hand_nn"
path_to_src: "/home/rakita/catkin_ws/src/relaxed_ik/src"
axis_types: [ [ "z", "z", "z", "z", "z", "z", "z" ] ]
velocity_limits: [ 2.175, 2.175, 2.175, 2.175, 2.61, 2.61, 2.61 ]
joint_limits: [ [-2.8973,2.8973], [-1.7628,1.7628], [-2.8973,2.8973], [-3.0718,-0.0698], [-2.8973,2.8973], [-0.0175,3.7525], [-2.8973,2.8973] ]
displacements: [ [ [0.0,0.0,0.0], [0.0,-0.316,0.0], [0.0825,0.0,0.0], [-0.0825,0.384,0.0], [0.0,0.0,0.0], [0.088,0.0,0.0], [0.0,0.0,0.107], [0.0,0.0,0.0] ] ]
disp_offsets: [ [0.0,0.0,0.333] ]
rot_offsets: [ [ [0.0,0.0,0.0], [-1.57079632679,0.0,0.0], [1.57079632679,0.0,0.0], [1.57079632679,0.0,0.0], [-1.57079632679,0.0,0.0], [1.57079632679,0.0,0.0], [1.57079632679,0.0,0.0], [0.0,0.0,0.0] ] ]
joint_types: [ [ "revolute", "revolute", "revolute", "revolute", "revolute", "revolute", "revolute", "fixed" ] ]
joint_state_define_func_file: "panda_arm_hand_joint_state_define"
