urdf_file_name: "sawyer.urdf"
fixed_frame: "base"
joint_names: [ [ "robot_offset", "right_arm_mount", "right_j0", "right_j1", "right_j2", "right_j3", "right_j4", "right_j5", "right_j6" ] ]
joint_ordering: [ "right_j0", "right_j1", "right_j2", "right_j3", "right_j4", "right_j5", "right_j6" ]
ee_fixed_joints: [ "right_hand" ]
starting_config: [ 0.0485546875, -0.462344726562, -2.20701074219, 1.53922558594, -1.1990625, -1.25713183594, 0.975064453125 ]
collision_file_name: "collision_sawyer.yaml"
collision_nn_file: "sawyer_nn"
path_to_src: "/home/rakita/catkin_ws/src/relaxed_ik/src"
axis_types: [ [ "z", "z", "z", "z", "z", "z", "z" ] ]
velocity_limits: [ 1.74, 1.328, 1.957, 1.957, 3.485, 3.485, 4.545 ]
joint_limits: [ [-3.0503,3.0503], [-3.8095,2.2736], [-3.0426,3.0426], [-3.0439,3.0439], [-2.9761,2.9761], [-2.9761,2.9761], [-4.7124,4.7124] ]
displacements: [ [ [0.0,0.0,0.08], [0.081,0.05,0.237], [0.0,-0.14,0.1425], [0.0,-0.042,0.26], [0.0,-0.125,-0.1265], [0.0,0.031,0.275], [0.0,-0.11,0.1053], [0.0,0.0,0.0245] ] ]
disp_offsets: [ [0.0,0.0,0.0] ]
rot_offsets: [ [ [0.0,0.0,0.0], [0.0,0.0,0.0], [-1.57079632679,1.57079632679,0.0], [1.57079632679,0.0,0.0], [-1.57079632679,0.0,0.0], [1.57079632679,0.0,0.0], [-1.57079632679,0.0,0.0], [-1.57079632679,-0.17453,3.1416] ] ]
joint_types: [ [ "fixed", "revolute", "revolute", "revolute", "revolute", "revolute", "revolute", "revolute" ] ]
joint_state_define_func_file: "sawyer_joint_state_define"
