robot_link_radius: 0.05
sample_states: [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
[-0.013823007660000108, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.013823007660000108, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.06911503829999965, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.29279643497999963, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.5717698623, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.7389025912799996, 0.0, 0.0, 0.0, 0.0, 0.0],
[0.9060353202600009, 0.0, 0.0, 0.0, 0.0, 0.0],
[1.12846007988, 0.0, 0.0, 0.0, 0.0, 0.0],
[1.2955928088599995, 0.0, 0.0, 0.0, 0.0, 0.0],
[1.462725537839999, 0.0, 0.0, 0.0, 0.0, 0.0],
[1.6575042821400006, 0.0, 0.0, 0.0, 0.0, 0.0],
[1.8246370111199992, 0.0, 0.0, 0.0, 0.0, 0.0],
[2.13125645376, 0.0, 0.0, 0.0, 0.0, 0.0],
[2.577362610059999, 0.0, 0.0, 0.0, 0.0, 0.0],
[2.828690022059999, 0.0, 0.0, 0.0, 0.0, 0.0],
[2.8563360373799993, 0.0, 0.0, 0.0, 0.0, 0.0],
[2.93927408334, 0.0, 0.0, 0.0, 0.0, 0.0],
[3.60780499926, 0.0, 0.0, 0.0, 0.0, 0.0],
[4.221043884539999, 0.0, 0.0, 0.0, 0.0, 0.0],
[4.861928785140001, 0.0, 0.0, 0.0, 0.0, 0.0],
[5.252742910800001, 0.0, 0.0, 0.0, 0.0, 0.0],
[5.47516767042, 0.0, 0.0, 0.0, 0.0, 0.0],
[5.697592430040001, 0.0, 0.0, 0.0, 0.0, 0.0],
[6.06076054038, 0.0, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 0.0, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 0.09801769068000077, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 0.15330972131999943, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 0.29279643497999963, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 0.45992916395999917, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 0.5428672099199998, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 0.7389025912799996, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 0.9336813355800002, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 1.01661938154, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 1.1008140645600006, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 1.1837521105199995, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 1.2679467935400002, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 1.3797874918800002, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 1.4350795225199997, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 1.462725537839999, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 1.5469202208599997, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 1.57456623618, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 1.7140529498400001, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 1.8246370111199992, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 2.0206723924800007, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 2.2983891827400003, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 2.493167927040001, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 2.6615572930800004, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 2.7721413543599995, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 2.828690022059999, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 2.35493785044, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 2.075964423120001, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 1.8811856788200005, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 1.57456623618, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 1.2126547629000006, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 0.7665486066000007, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 0.1256637060000001, 0.0, 0.0, 0.0, 0.0],
[6.2831853, -0.23624776728000008, 0.0, 0.0, 0.0, 0.0],
[6.2831853, -0.5994158776200003, 0.0, 0.0, 0.0, 0.0],
[6.2831853, -0.79419462192, 0.0, 0.0, 0.0, 0.0],
[6.2831853, -1.12846007988, 0.0, 0.0, 0.0, 0.0],
[6.2831853, -1.5180175684800004, 0.0, 0.0, 0.0, 0.0],
[6.2831853, -1.7693449804799997, 0.0, 0.0, 0.0, 0.0],
[6.2831853, -1.7969909957999999, 0.0, 0.0, 0.0, 0.0],
[6.2831853, -1.9088316941399999, 0.0, 0.0, 0.0, 0.0],
[6.2831853, -1.1837521105200004, 0.0, 0.0, 0.0, 0.0],
[6.2831853, -0.7389025912800005, 0.0, 0.0, 0.0, 0.0],
[6.2831853, -0.48757517928000027, 0.0, 0.0, 0.0, 0.0],
[6.2831853, -0.18095573664000053, 0.0, 0.0, 0.0, 0.0],
[6.2831853, -0.013823007660000108, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 0.013823007660000108, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 0.18095573663999964, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 0.20860175195999897, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.0, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.012566370600000099, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.037699111800000296, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.06283185300000049, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.0879645941999998, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.1130973354, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.1382300766000002, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.1633628178000004, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.1884955590000006, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.2136283001999999, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.2387610414000001, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.2638937826000003, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.2890265238000005, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.3141592650000007, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.3392920062, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.3644247474000002, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.3895574886000004, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.4146902298000006, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.4398229710000008, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.4649557122000001, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.4900884534000003, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.5152211946000005, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.5403539358000007, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.5654866770000009, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.5906194182000002, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.6157521594000004, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.6408849006000006, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.6547079082600007, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.68235392358, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 0.9613273509000004, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 1.1561060951999993, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 1.3508848395000008, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 1.5180175684800004, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 1.7969909958000008, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 1.8811856788200005, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 1.9917697400999996, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 2.15890246908, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 2.2430971521, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 2.3260351980600005, 0.0, 0.0, 0.0],
[6.2831853, 0.23624776728000008, 2.493167927040001, 0.0, 0.0, 0.0]]
boxes:
spheres:
ellipsoids:
capsules:
cylinders:

