robot_link_radius: 0.05
sample_states: [ [-0.72980141,  1.82473686,  0.05004675, -1.17187243, -2.47790277,  0.14499504, -1.35150909, -1.13954413],
[ 2.11062304,  1.36317257, -0.00849951, -1.35405792, -0.74341992, -0.83897834, -0.27372747, -0.70766507],
[-1.88223643, -0.66435388,  0.09899378, 0.607408, -1.47676658, -1.58920619, 1.18318145,  0.99929842],
[ 0.07338114,  0.18082921, -0.03380994, -0.6421907,  -0.59007974,  0.52447233, -1.16469675, -0.34811331] ]
training_states:
problem_states:
boxes:
  - name: box1
    parameters: [1,1,0.1]
    coordinate_frame: 0
    rotation: [0,0,0]
    translation: [1,0,0]
spheres:
  - name: sphere1
    parameters: .02
    coordinate_frame: 9
    rotation: [0,0,0]
    translation: [.115,0.025,-0.053]
ellipsoids:
capsules:
cylinders:
